CFLAGS=-Ofast -lm -std=c99 -pedantic -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition -Wno-unused-result -Wsign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration

all:
	$(CC) -o seatids seatids.c $(CFLAGS)
