CC=gcc
CFLAGS=-Ofast -std=c99 -Wpedantic -Wall -Wextra -Wmissing-prototypes \
	-Wstrict-prototypes -Wold-style-definition -Wno-unused-result \
	-Wsign-compare -Wno-unused-parameter -Wno-missing-field-initializers \
	-Werror=implicit-function-declaration -Wundef -Wshadow -Wmissing-declarations

all:
	$(CC) -o puzzle-1 puzzle-1.c $(CFLAGS)
	$(CC) -o puzzle-2 puzzle-2.c $(CFLAGS)
